version: "3.8"
services:
  php:
    image: ghcr.io/sylius/sylius-php:8.2-fixuid-alpine
    user: ${DOCKER_USER:-1000:1000}
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APP_DEBUG: 0
      APP_ENV: ${ENV:-prod}
      APP_SECRET: EDITME
      DATABASE_URL: "mysql://root@mysql/sylius_%kernel.environment%"
      MAILER_URL: null://null
      MESSENGER_TRANSPORT_DSN: doctrine://default
      SYLIUS_MESSENGER_TRANSPORT_MAIN_DSN: doctrine://default
      SYLIUS_MESSENGER_TRANSPORT_MAIN_FAILED_DSN: doctrine://default?queue_name=main_failed
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_DSN: doctrine://default?queue_name=catalog_promotion_removal
      SYLIUS_MESSENGER_TRANSPORT_CATALOG_PROMOTION_REMOVAL_FAILED_DSN: doctrine://default?queue_name=catalog_promotion_removal_failed
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE:-UTC}
    volumes:
      - .:/srv/sylius:rw,cached
      # if you develop on Linux, you may use a bind-mounted host directory instead
#      - ./var:/srv/sylius/var:rw
      - ./public:/srv/sylius/public:rw,delegated
      # if you develop on Linux, you may use a bind-mounted host directory instead
#      - ./public/media:/srv/sylius/public/media:rw
      - public-media:/srv/sylius/public/media:rw
  mysql:
    volumes:
      - mysql-data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
  nginx:
    volumes:
      - ./public:/srv/sylius/public:ro
      # if you develop on Linux, you may use a bind-mounted host directory instead
#      - ./public/media:/srv/sylius/public/media:ro
      - public-media:/srv/sylius/public/media:ro,nocopy
    ports:
      - "80:80"
  nodejs:
    image: node:${NODE_VERSION:-16}-alpine
    user: ${DOCKER_USER:-1000:1000}
    working_dir: /srv/sylius
    entrypoint: [ "/bin/sh","-c" ]
    command:
      - |
        yarn install
        yarn build
    volumes:
      - .:/srv/sylius:rw,cached
      - ./public:/srv/sylius/public:rw,delegated
volumes:
  mysql-data:
  public-media:
