version: "3.8"
services:
  php:
    image: ghcr.io/sylius/sylius-php:8.2-fixuid-xdebug-alpine
    environment:
      APP_DEBUG: 1
      MAILER_URL: smtp://mailhog:1025
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        client_port=9003
        log=/dev/stdout
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=sylius
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mailhog:
    # do not use in production!
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
